// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brdercjlgogymceekfon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZGVyY2psZ29neW1jZWVrZm9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDQ4NTgsImV4cCI6MjA1Nzk4MDg1OH0.uzlH3R4iIAlSTXX3EwdZT6r42ywGL9XgR6cj6Bcc13Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);